config/routes.rb
ContactDemo::Application.routes.draw do
  

  resources :contact_messages

  root :to => 'pages#home'

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :balance, :number
   validate :price_must_be_at_least_a_cent
  
  def withdraw(amount)
    adjust_balance_and_save(-amount)
  end
  
  def deposit(amount)
    adjust_balance_and_save(amount)
  end
  
  private
  #Vorzeichen wird geändert durch "-" in withdraw-Methode
    def adjust_balance_and_save(amount)
        self.balance += amount
      save!
    end
    
    def price_must_be_at_least_a_cent
      errors.add(:balance, "is negative") if balance < 0
    end
end

app/models/contact_message.rb
class ContactMessage < ActiveRecord::Base
after_initialize :bombing


  
  attr_accessible :email, :message, :name
  
  
  
  validates :name, length: {:minimum => 2}
  
  validates :email,
            format: /^([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})$/i
            
  validates :message, presence: true
  
 
  after_find do |contact_message|
    puts "you have received a message"
  end
  
  def bombing
    puts "Yes it works"
  end  



  
  
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/contact_messages_controller.rb
#encoding: utf-8
class ContactMessagesController < ApplicationController

http_basic_authenticate_with  :name => ENV["ADMIN_LOGIN"],
                              :password => ENV["ADMIN_PWD"],
                              :except => [:new, :create]
  # GET /contact_messages
  # GET /contact_messages.json
  def index
    @contact_messages = ContactMessage.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contact_messages }
    end
  end

  # GET /contact_messages/1
  # GET /contact_messages/1.json
  def show
    @contact_message = ContactMessage.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact_message }
    end
  end

  # GET /contact_messages/new
  # GET /contact_messages/new.json
  def new
    @contact_message = ContactMessage.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact_message }
    end
  end

  # GET /contact_messages/1/edit
  def edit
    @contact_message = ContactMessage.find(params[:id])
  end

  # POST /contact_messages
  # POST /contact_messages.json
  def create
    @contact_message = ContactMessage.new(params[:contact_message])
    if @contact_message.save
      ContactMailer.confirmation(@contact_message.email).deliver
      ContactMailer.inquiry(@contact_message).deliver
      redirect_to root_url, notice: 'Danke für Ihre Nachricht. Sie erhalten in einigen Sekunden eine Email zur Bestätigung.'
    else
      render action: 'new'
    end
  end

  # PUT /contact_messages/1
  # PUT /contact_messages/1.json
  def update
    @contact_message = ContactMessage.find(params[:id])

    respond_to do |format|
      if @contact_message.update_attributes(params[:contact_message])
        format.html { redirect_to @contact_message, notice: 'Contact message was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact_message.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_messages/1
  # DELETE /contact_messages/1.json
  def destroy
    @contact_message = ContactMessage.find(params[:id])
    @contact_message.destroy

    respond_to do |format|
      format.html { redirect_to contact_messages_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contact_messages_helper.rb
module ContactMessagesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/contact_messages/_form.html.erb
<%= form_for(@contact_message) do |f| %>
<div class="modal-body">
  <% if @contact_message.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact_message.errors.count, "error") %> prohibited this contact_message from being saved:</h2>

      <ul>
      <% @contact_message.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message, "Nachricht" %><br />
    <%= f.text_area :message %>
  </div>
  <div>
  
    <%= f.submit "Anfrage senden", class: 'btn btn-info' %>
  </div>
<% end %>

app/views/contact_messages/_index.html.erb
<% @contact_messages.each do |contact_message| %>
  <tr valign="top">
    <td style="padding: 15px 15px;"><%= contact_message.name %></td>
    <td style="padding: 15px 15px;"><%= contact_message.email %></td>
    <td style="text-align: justify; padding: 15px 15px;"><%= truncate(contact_message.message, length: 200, separator: " ") %></td>
    
    <td><%= link_to 'Anzeigen', contact_message %> <%= link_to 'Bearbeiten', edit_contact_message_path(contact_message) %> <%= link_to 'Löschen', contact_message, method: :delete, data: { confirm: 'Bist Du sicher?' } %></td>
    
    </tr> 
    
<% end %>
     

  

app/views/contact_messages/edit.html.erb
<h1>Kontaktanfrage bearbeiten</h1>

<%= render 'form' %>

<%= link_to 'Anzeigen', @contact_message %> |
<%= link_to 'Zurück', contact_messages_path %>

app/views/contact_messages/index.html.erb
<h1>Liste der Anfragen</h1>
<div class="container">
<div class="well">
<%= link_to 'Kontaktanfrage von Hand eintragen', new_contact_message_path %>
<span style="color: #767676; float: right;">Zum Bearbeiten auf Eintrag gehen:</span>
</div>
<div class="table-responsive">
<table class="table table-striped">
 <thead>
  <tr>
    <th style="padding-left: 15px; text-align: left;">Name</th>
    <th style="padding-left: 15px; text-align: left;">Email</th>
    <th style="padding-left: 15px; text-align: left;">Nachricht</th>
    
 </thead>
  <tbody>
      <%= render "index" %>
  </tbody>
  


</table>
</div>
</div>

app/views/contact_messages/new.html.erb
<div class="modal-header">
<h1>Kontaktieren Sie uns:</h1>
</div>

<%= render 'form' %>

<%= link_to 'Zurück', contact_messages_path %>

app/views/contact_messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @contact_message.name %>
</p>

<p>
  <b>Email:</b>
  <%= @contact_message.email %>
</p>

<p>
  <b>Message:</b>
  <%= @contact_message.message %>
</p>


<%= link_to 'Edit', edit_contact_message_path(@contact_message) %> |
<%= link_to 'Back', contact_messages_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <p id="bong">Robert Wolf - 2013</p>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
     
      <nav>
        <ul id="logo">
          <li><%= link_to "Home", root_path %></li>
        </ul>
        <ul class="nav pull-right"> 
          <li id="bong"> <%= link_to "Admin (Nachrichten verwalten)", contact_messages_path %></li>
       </ul>   
      </nav>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Contact Demo incl. Mail Confirmation</title>
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>

<body>
<%= render 'layouts/header' %>
  <div class="container">
  
    <%= yield %>
    <%= render 'layouts/footer' %> 
  </div>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>


</body>
</html>

app/views/layouts/contact.html.erb
<!DOCTYPE html>
<html>
<body>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<h1>KONTAKT:</h1>
<p id="notice"><%= notice %>
<p id="bong"><b>Robert Wolf<br>
Am Fenn 14<br>
10569 Berlin</b>
</p>
<br>
<p id="bong"><b>Telefon: 030 45 000 589</b></p>
<br>
<p style="font-size:18px;"><b><%= link_to "Senden Sie uns eine Nachricht >>", new_contact_message_path %></b></p>
<br>
<br>
<p></p>